### ISSUE TITLE
Hidden Paypal form

### ISSUE THREAD

**Issue by Tibladar** [supertuxkart/stk-wiki-theme#2]
There's an old paypal form on all sites in the footer which is hidden from the user for quite some time.
The issue is that even though it's hidden the tracking pixel from Paypal is always loaded.

https://github.com/supertuxkart/stk-wiki-theme/blob/79eb1babaf02a27a5f3242cf2bd20cff454c1385/SuperTuxKartTemplate.php#L132-L169

If the donation banner in the footer is not going to be used I suggest removing/commenting out the paypal code to reduce tracking and page load time.

Didn't create a PR, wanted to hear some opinions first.

**Comment by Benau** [comment]
yes we no longer using paypal for donation
